version: "3"

services:
  tic-tac-toe:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - tic-tac-toe:/var/lib/postgresql/data
  rabbit-mq:
    image: rabbitmq
    command: rabbitmq-server
    ports:
      - 5672:5672
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 5
volumes:
  tic-tac-toe:
